// app/order-tracking/page.tsx
"use client";

import { Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Icon } from "@iconify/react";
import { useOrderTracking } from "@/lib/hooks/useOrders";

export default function OrderTrackingPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-50 via-blue-50/30 to-slate-50">
          <div className="flex items-center gap-3 text-gray-500">
            <Icon icon="svg-spinners:ring-resize" className="w-6 h-6 text-[#012068]" />
            <span className="text-sm font-medium">Loading...</span>
          </div>
        </div>
      }
    >
      <OrderTrackingContent />
    </Suspense>
  );
}

function OrderTrackingContent() {
  const searchParams = useSearchParams();
  const initialSaleCode = searchParams.get("sale_code") || "";
  const [saleCode, setSaleCode] = useState(initialSaleCode);
  const [submittedCode, setSubmittedCode] = useState(initialSaleCode);

  const {
    data: orderStatus,
    isLoading,
    error,
  } = useOrderTracking(submittedCode, !!submittedCode);
  const errorMsg = error ? error.message : "";

  const steps = [
    { label: "Order Placed", icon: "mdi:receipt-text-outline" },
    { label: "Store Arrived", icon: "mdi:storefront-outline" },
    { label: "On The Way", icon: "mdi:truck-fast-outline" },
    { label: "Delivered", icon: "mdi:home-check-outline" },
  ];

  const trackOrder = () => {
    if (!saleCode.trim()) return;
    setSubmittedCode(saleCode.trim());
  };

  const formatDate = (dateString: string) =>
    new Date(dateString).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });

  const getStatusText = (status: number | null) =>
    (
      {
        null: "Processing",
        1: "Store Arrived",
        2: "On The Way",
        3: "Delivered",
        4: "Not Reachable",
        5: "Not Received",
      } as Record<string, string>
    )[String(status)] || "Processing";

  const getStatusBadgeClass = (status: number | null) =>
    (
      {
        null: "bg-blue-50 text-blue-700 ring-blue-200",
        1: "bg-amber-50 text-amber-700 ring-amber-200",
        2: "bg-orange-50 text-orange-700 ring-orange-200",
        3: "bg-emerald-50 text-emerald-700 ring-emerald-200",
        4: "bg-red-50 text-red-700 ring-red-200",
        5: "bg-red-50 text-red-700 ring-red-200",
      } as Record<string, string>
    )[String(status)] || "bg-blue-50 text-blue-700 ring-blue-200";

  const getStatusIcon = (status: number | null) =>
    (
      {
        null: "mdi:clock-outline",
        1: "mdi:storefront-outline",
        2: "mdi:truck-fast-outline",
        3: "mdi:check-circle",
        4: "mdi:phone-off-outline",
        5: "mdi:alert-circle-outline",
      } as Record<string, string>
    )[String(status)] || "mdi:clock-outline";

  const getCurrentStep = () =>
    ({ null: 0, 1: 1, 2: 2, 3: 3, 4: 2, 5: 2 } as Record<string, number>)[
      String(orderStatus?.delivery_status)
    ] ?? 0;

  const currentStep = getCurrentStep();

  return (
    <section className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/30 to-slate-50 py-8 md:py-12 relative overflow-hidden">
    

      <div className="container mx-auto px-4 max-w-3xl relative">
        {/* Header */}
        <div className="text-center mb-8 md:mb-10">
          <div className="inline-flex items-center justify-center w-16 h-16 md:w-20 md:h-20 rounded-2xl bg-gradient-to-br from-[#012068] to-[#5360A7] mb-4 shadow-lg shadow-[#012068]/25 rotate-3 hover:rotate-0 transition-transform duration-300">
            <Icon
              icon="mdi:package-variant-closed"
              className="w-9 h-9 md:w-10 md:h-10 text-white"
            />
          </div>
          <h1 className="text-2xl md:text-3xl font-bold text-gray-900 mb-2">
            Track Your Order
          </h1>
          <p className="text-sm md:text-base text-gray-500 max-w-md mx-auto">
            Enter your order code below to see real-time delivery updates
          </p>
        </div>

        {/* Search form */}
        <form
          onSubmit={(e) => {
            e.preventDefault();
            trackOrder();
          }}
          className="relative bg-white rounded-2xl shadow-lg shadow-gray-200/50 border border-gray-100 p-2 mb-6 md:mb-8 flex items-center gap-2"
        >
          <div className="relative flex-1">
            <Icon
              icon="mdi:magnify"
              className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400 pointer-events-none"
            />
            <input
              type="text"
              className="w-full pl-11 pr-4 py-3 bg-transparent text-gray-900 focus:outline-none placeholder-gray-400 text-sm md:text-base"
              placeholder="e.g. 2602224134"
              value={saleCode}
              onChange={(e) => setSaleCode(e.target.value)}
              required
            />
          </div>
          <button
            type="submit"
            disabled={isLoading || !saleCode.trim()}
            className="group bg-gradient-to-br from-[#012068] to-[#5360A7] hover:shadow-lg hover:shadow-[#012068]/30 text-white font-semibold px-5 md:px-6 py-3 rounded-xl transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 whitespace-nowrap active:scale-95"
          >
            {isLoading ? (
              <Icon icon="svg-spinners:ring-resize" className="w-5 h-5" />
            ) : (
              <Icon
                icon="mdi:crosshairs-gps"
                className="w-5 h-5 group-hover:rotate-90 transition-transform duration-300"
              />
            )}
            <span className="text-sm md:text-base">
              {isLoading ? "Tracking..." : "Track"}
            </span>
          </button>
        </form>

        {/* Loading skeleton */}
        {isLoading && !orderStatus && (
          <div className="space-y-5 animate-pulse">
            <div className="bg-white rounded-2xl h-32 border border-gray-100" />
            <div className="bg-white rounded-2xl h-40 border border-gray-100" />
            <div className="bg-white rounded-2xl h-48 border border-gray-100" />
          </div>
        )}

        {/* Error state */}
        {errorMsg && (
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-8 md:p-10 text-center animate-fade-in">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-red-50 mb-4">
              <Icon
                icon="mdi:package-variant-remove"
                className="w-8 h-8 text-red-500"
              />
            </div>
            <h3 className="text-lg md:text-xl font-bold text-gray-900 mb-2">
              Order Not Found
            </h3>
            <p className="text-sm text-gray-500 mb-6 max-w-sm mx-auto">
              {errorMsg}
            </p>
            <button
              onClick={() => {
                setSaleCode("");
                setSubmittedCode("");
              }}
              className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#012068] text-white text-sm font-semibold rounded-xl hover:bg-[#012068]/90 shadow-md shadow-[#012068]/20 active:scale-95 transition-all"
            >
              <Icon icon="mdi:refresh" className="w-4 h-4" />
              Try Again
            </button>
          </div>
        )}

        {/* Order details */}
        {!isLoading && orderStatus && (
          <div className="space-y-5 animate-fade-in">
            {/* Order Summary Card */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
              <div className="relative bg-gradient-to-br from-[#012068] via-[#1a3585] to-[#5360A7] px-5 md:px-6 py-5 overflow-hidden">
                <div className="absolute -top-10 -right-10 w-40 h-40 bg-white/5 rounded-full blur-2xl" />
                <div className="absolute bottom-0 left-0 w-32 h-32 bg-[#13a89e]/10 rounded-full blur-2xl" />
                <div className="relative flex items-center justify-between flex-wrap gap-4">
                  <div>
                    <p className="text-white/60 text-[10px] md:text-xs font-semibold uppercase tracking-widest mb-1">
                      Order Code
                    </p>
                    <p className="text-white text-xl md:text-2xl font-bold tracking-tight">
                      #{orderStatus.sale_code}
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="text-white/60 text-[10px] md:text-xs font-semibold uppercase tracking-widest mb-1">
                      Order Date
                    </p>
                    <p className="text-white text-sm md:text-base font-semibold">
                      {formatDate(orderStatus.sale_date)}
                    </p>
                  </div>
                </div>
              </div>

              <div className="divide-y divide-gray-100">
                <div className="px-5 md:px-6 py-4 flex items-center justify-between">
                  <span className="flex items-center gap-2 text-sm text-gray-500">
                    <Icon icon="mdi:information-outline" className="w-4 h-4" />
                    Current Status
                  </span>
                  <span
                    className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold ring-1 ring-inset ${getStatusBadgeClass(
                      orderStatus.delivery_status
                    )}`}
                  >
                    <Icon
                      icon={getStatusIcon(orderStatus.delivery_status)}
                      className="w-3.5 h-3.5"
                    />
                    {getStatusText(orderStatus.delivery_status)}
                  </span>
                </div>
                <div className="px-5 md:px-6 py-4 flex items-center justify-between">
                  <span className="flex items-center gap-2 text-sm text-gray-500">
                    <Icon icon="mdi:credit-card-outline" className="w-4 h-4" />
                    Payment
                  </span>
                  <span className="text-sm font-semibold text-gray-800">
                    {orderStatus.payment_method?.name}
                  </span>
                </div>
                <div className="px-5 md:px-6 py-4 flex items-center justify-between bg-gradient-to-r from-[#012068]/5 to-transparent">
                  <span className="flex items-center gap-2 text-sm font-semibold text-gray-700">
                    <Icon icon="mdi:cash-multiple" className="w-4 h-4" />
                    Total Amount
                  </span>
                  <span className="text-lg md:text-xl font-bold text-[#012068] tabular-nums">
                    ৳ {Number(orderStatus.total).toFixed(2)}
                  </span>
                </div>
              </div>
            </div>

            {/* Progress Timeline */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 md:p-6">
              <div className="flex items-center gap-2 mb-6">
                <span className="block w-1 h-5 rounded-full bg-gradient-to-b from-[#5360A7] to-[#012068]" />
                <h3 className="text-sm md:text-base font-bold text-gray-900">
                  Delivery Progress
                </h3>
              </div>

              <div className="relative">
                {/* Background track */}
                <div className="absolute top-5 md:top-6 left-0 right-0 h-1 bg-gray-100 rounded-full mx-6" />
                {/* Progress fill */}
                <div
                  className="absolute top-5 md:top-6 left-0 h-1 bg-gradient-to-r from-[#012068] to-[#13a89e] rounded-full transition-all duration-700 ease-out mx-6"
                  style={{
                    width:
                      currentStep === 0
                        ? "0%"
                        : `calc(${(currentStep / (steps.length - 1)) * 100}% - ${
                            (currentStep / (steps.length - 1)) * 48
                          }px)`,
                  }}
                />

                <div className="relative flex items-start justify-between">
                  {steps.map((step, index) => {
                    const isDone = index < currentStep;
                    const isActive = index === currentStep;
                    const isReached = index <= currentStep;
                    return (
                      <div
                        key={index}
                        className="flex flex-col items-center flex-1 min-w-0"
                      >
                        <div
                          className={`relative w-10 h-10 md:w-12 md:h-12 rounded-full flex items-center justify-center transition-all duration-300 ${
                            isReached
                              ? "bg-gradient-to-br from-[#012068] to-[#5360A7] text-white shadow-lg shadow-[#012068]/30"
                              : "bg-white text-gray-400 ring-2 ring-gray-200"
                          }`}
                        >
                          {isActive && (
                            <span className="absolute inset-0 rounded-full bg-[#012068]/30 animate-ping" />
                          )}
                          {isDone ? (
                            <Icon icon="mdi:check-bold" className="w-5 h-5" />
                          ) : (
                            <Icon
                              icon={step.icon}
                              className="w-4 h-4 md:w-5 md:h-5"
                            />
                          )}
                        </div>
                        <p
                          className={`mt-2 text-[10px] md:text-xs font-semibold text-center leading-tight px-1 ${
                            isReached ? "text-[#012068]" : "text-gray-400"
                          }`}
                        >
                          {step.label}
                        </p>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

            {/* Products */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
              <div className="px-5 md:px-6 py-4 border-b border-gray-100 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="block w-1 h-5 rounded-full bg-gradient-to-b from-[#5360A7] to-[#012068]" />
                  <h3 className="text-sm md:text-base font-bold text-gray-900">
                    Ordered Items
                  </h3>
                </div>
                <span className="inline-flex items-center justify-center min-w-[24px] h-6 px-2 rounded-full bg-[#012068]/10 text-[#012068] text-xs font-bold">
                  {orderStatus.sale_products?.length}
                </span>
              </div>
              <ul className="divide-y divide-gray-50">
                {orderStatus.sale_products?.map((product, i) => (
                  <li
                    key={i}
                    className="px-5 md:px-6 py-3.5 flex items-center justify-between gap-3 hover:bg-gray-50/50 transition-colors"
                  >
                    <div className="flex items-center gap-3 flex-1 min-w-0">
                      <div className="flex-shrink-0 w-10 h-10 rounded-lg bg-gradient-to-br from-gray-50 to-gray-100 flex items-center justify-center ring-1 ring-gray-100">
                        <Icon
                          icon="mdi:pill"
                          className="w-5 h-5 text-[#012068]/60"
                        />
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-semibold text-gray-900 truncate">
                          {product.product_name}
                        </p>
                        <p className="text-xs text-gray-500 mt-0.5">
                          Qty: {product.total_quantity} · ৳
                          {Number(product.ecom_final_selling_price || 0).toFixed(2)}
                          /unit
                        </p>
                      </div>
                    </div>
                    <p className="text-sm font-bold text-gray-900 whitespace-nowrap tabular-nums">
                      ৳ {Number(product.total).toFixed(2)}
                    </p>
                  </li>
                ))}
              </ul>
              <div className="px-5 md:px-6 py-4 bg-gradient-to-r from-[#012068]/5 via-[#13a89e]/5 to-transparent flex items-center justify-between border-t border-gray-100">
                <span className="text-sm font-bold text-gray-900">Total</span>
                <span className="text-lg md:text-xl font-bold text-[#012068] tabular-nums">
                  ৳ {Number(orderStatus.total).toFixed(2)}
                </span>
              </div>
            </div>

            {/* Shipping address */}
            {orderStatus.billing_address && (
              <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 md:p-6">
                <div className="flex items-center gap-2 mb-4">
                  <span className="block w-1 h-5 rounded-full bg-gradient-to-b from-[#5360A7] to-[#012068]" />
                  <h3 className="text-sm md:text-base font-bold text-gray-900">
                    Shipping Address
                  </h3>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#012068]/10 to-[#13a89e]/10 flex items-center justify-center flex-shrink-0">
                    <Icon
                      icon="mdi:map-marker-outline"
                      className="w-5 h-5 text-[#012068]"
                    />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm md:text-base font-semibold text-gray-900">
                      {orderStatus.billing_address.full_name}
                    </p>
                    <p className="text-sm text-gray-500 mt-1">
                      {orderStatus.billing_address.address}
                    </p>
                    <p className="inline-flex items-center gap-1.5 text-sm text-gray-600 mt-1.5">
                      <Icon icon="mdi:phone" className="w-3.5 h-3.5" />
                      {orderStatus.billing_address.mobile}
                    </p>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </section>
  );
}

// app/pages/order-tracking.vue
<template>
  <NuxtLayout>
    <section class="min-h-screen bg-gray-50 py-8">
      <div class="container mx-auto px-4 max-w-2xl">
        <!-- Search Section -->
        <div class="text-center mb-8">
          <div
            class="inline-flex items-center justify-center w-16 h-16 rounded-full bg-[#388072]/10 mb-4"
          >
            <svg
              class="w-8 h-8 text-[#388072]"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
              />
            </svg>
          </div>
          <h1 class="text-2xl font-bold text-gray-800 mb-1">
            Track Your Order
          </h1>
          <p class="text-sm text-gray-500">
            Enter your order code to check the delivery status
          </p>
        </div>

        <!-- Search Form -->
        <form @submit.prevent="trackOrder()" class="flex gap-3 mb-8">
          <input
            type="text"
            class="flex-1 px-4 py-3 bg-white text-gray-900 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-[#388072] transition-colors placeholder-gray-400"
            placeholder="e.g. 2602224134"
            v-model="sale_code"
            required
          />
          <button
            type="submit"
            :disabled="isLoading"
            class="bg-[#388072] hover:bg-[#2d6960] text-white font-semibold px-6 py-3 rounded-xl transition-colors disabled:opacity-50 flex items-center gap-2 whitespace-nowrap"
          >
            <svg
              v-if="isLoading"
              class="animate-spin w-5 h-5"
              fill="none"
              viewBox="0 0 24 24"
            >
              <circle
                class="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                stroke-width="4"
              />
              <path
                class="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
              />
            </svg>
            <span>{{ isLoading ? "Tracking..." : "Track" }}</span>
          </button>
        </form>

        <!-- Error State -->
        <div
          v-if="errorMsg"
          class="bg-white rounded-2xl shadow-sm border border-gray-100 p-8 text-center animate-fade-in"
        >
          <div
            class="inline-flex items-center justify-center w-20 h-20 rounded-full bg-red-50 mb-5"
          >
            <svg
              class="w-10 h-10 text-red-400"
              fill="none"
              stroke="currentColor"
              stroke-width="1.5"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
          </div>
          <h3 class="text-lg font-bold text-gray-800 mb-2">Order Not Found</h3>
          <p class="text-sm text-gray-500 mb-5">
            We couldn't find any order with that code. Please double-check and
            try again.
          </p>
          <button
            @click="sale_code = ''; errorMsg = '';"
            class="inline-flex items-center gap-2 px-5 py-2.5 bg-[#388072] text-white text-sm font-semibold rounded-xl hover:bg-[#2d6960] transition-colors"
          >
            <svg
              class="w-4 h-4"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182"
              />
            </svg>
            Try Again
          </button>
        </div>

        <!-- Order Results -->
        <div v-if="!isLoading && orderStatus" class="space-y-5 animate-fade-in">
          <!-- Order Info Header -->
          <div
            class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden"
          >
            <div
              class="bg-[#388072] px-5 py-4 flex items-center justify-between"
            >
              <div>
                <p
                  class="text-white/70 text-xs font-medium uppercase tracking-wider"
                >
                  Order Code
                </p>
                <p class="text-white text-lg font-bold">
                  #{{ orderStatus.sale_code }}
                </p>
              </div>
              <div class="text-right">
                <p
                  class="text-white/70 text-xs font-medium uppercase tracking-wider"
                >
                  Order Date
                </p>
                <p class="text-white text-sm font-semibold">
                  {{ formatDate(orderStatus.sale_date) }}
                </p>
              </div>
            </div>

            <!-- Status Badge -->
            <div
              class="px-5 py-4 flex items-center justify-between border-b border-gray-100"
            >
              <span class="text-sm text-gray-500">Current Status</span>
              <span
                :class="getStatusBadgeClass(orderStatus.delivery_status)"
                class="px-3 py-1 rounded-full text-xs font-semibold"
              >
                {{ getStatusText(orderStatus.delivery_status) }}
              </span>
            </div>

            <!-- Payment & Total -->
            <div
              class="px-5 py-3 flex items-center justify-between border-b border-gray-100"
            >
              <span class="text-sm text-gray-500">Payment</span>
              <span class="text-sm font-medium text-gray-700">
                {{ orderStatus.payment_method?.name }}
              </span>
            </div>
            <div class="px-5 py-3 flex items-center justify-between">
              <span class="text-sm text-gray-500">Total Amount</span>
              <span class="text-lg font-bold text-[#388072]">
                ৳ {{ Number(orderStatus.total).toFixed(2) }}
              </span>
            </div>
          </div>

          <!-- Progress Timeline -->
          <div
            class="bg-white rounded-2xl shadow-sm border border-gray-100 p-5"
          >
            <h3
              class="text-sm font-semibold text-gray-700 mb-5 uppercase tracking-wider"
            >
              Delivery Progress
            </h3>
            <div class="flex items-center justify-between">
              <template v-for="(step, index) in steps" :key="index">
                <!-- Step -->
                <div class="flex flex-col items-center" style="min-width: 60px">
                  <div
                    :class="[
                      'w-9 h-9 rounded-full flex items-center justify-center transition-all duration-300',
                      index <= getCurrentStep()
                        ? 'bg-[#388072] text-white shadow-md shadow-[#388072]/30'
                        : 'bg-gray-100 text-gray-400',
                    ]"
                  >
                    <svg
                      v-if="index < getCurrentStep()"
                      class="w-4 h-4"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                        clip-rule="evenodd"
                      />
                    </svg>
                    <span v-else class="text-xs font-bold">{{
                      index + 1
                    }}</span>
                  </div>
                  <p
                    class="mt-2 text-[10px] font-medium text-center leading-tight"
                    :class="
                      index <= getCurrentStep()
                        ? 'text-[#388072]'
                        : 'text-gray-400'
                    "
                  >
                    {{ step }}
                  </p>
                </div>
                <!-- Connector Line -->
                <div
                  v-if="index < steps.length - 1"
                  class="flex-1 h-[3px] mx-1 rounded-full transition-all duration-500"
                  :class="
                    index < getCurrentStep() ? 'bg-[#388072]' : 'bg-gray-200'
                  "
                ></div>
              </template>
            </div>
          </div>

          <!-- Products List -->
          <div
            class="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden"
          >
            <div class="px-5 py-4 border-b border-gray-100">
              <h3
                class="text-sm font-semibold text-gray-700 uppercase tracking-wider"
              >
                Ordered Items ({{ orderStatus.sale_products?.length }})
              </h3>
            </div>

            <div class="divide-y divide-gray-50">
              <div
                v-for="product in orderStatus.sale_products"
                :key="product.id"
                class="px-5 py-3 flex items-center justify-between"
              >
                <div class="flex-1 min-w-0 mr-3">
                  <p class="text-sm font-medium text-gray-800 truncate">
                    {{ product.product_name }}
                  </p>
                  <p class="text-xs text-gray-400 mt-0.5">
                    Qty: {{ product.total_quantity }} | ৳{{
                      Number(product.ecom_final_selling_price).toFixed(2)
                    }}/unit
                    <span class="text-[#388072] font-medium">
                      ({{
                        Number(product.ecom_discount_percentage).toFixed(0)
                      }}% off)
                    </span>
                  </p>
                </div>
                <p
                  class="text-sm font-semibold text-gray-800 whitespace-nowrap"
                >
                  ৳ {{ Number(product.total).toFixed(2) }}
                </p>
              </div>
            </div>

            <!-- Total -->
            <div
              class="px-5 py-4 bg-[#388072]/5 flex items-center justify-between"
            >
              <span class="text-sm font-bold text-gray-700">Total</span>
              <span class="text-lg font-bold text-[#388072]">
                ৳ {{ Number(orderStatus.total).toFixed(2) }}
              </span>
            </div>
          </div>

          <!-- Shipping Address -->
          <div
            v-if="orderStatus.billing_address"
            class="bg-white rounded-2xl shadow-sm border border-gray-100 p-5"
          >
            <h3
              class="text-sm font-semibold text-gray-700 uppercase tracking-wider mb-3"
            >
              Shipping Address
            </h3>
            <div class="flex items-start gap-3">
              <div
                class="w-8 h-8 rounded-full bg-[#388072]/10 flex items-center justify-center flex-shrink-0 mt-0.5"
              >
                <svg
                  class="w-4 h-4 text-[#388072]"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
                  />
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
                  />
                </svg>
              </div>
              <div>
                <p class="text-sm font-semibold text-gray-800">
                  {{ orderStatus.billing_address.full_name }}
                </p>
                <p class="text-sm text-gray-500">
                  {{ orderStatus.billing_address.address }}
                </p>
                <p class="text-sm text-gray-500">
                  {{ orderStatus.billing_address.mobile }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </NuxtLayout>
</template>

<script setup>
import { apiBasePharma } from "@/config";
import axios from "axios";

const route = useRoute();

const sale_code = ref(route.query.sale_code || "");
const orderStatus = ref(null);
const isLoading = ref(false);
const errorMsg = ref("");

const steps = ["Order Placed", "Store Arrived", "On The Way", "Delivered"];

const trackOrder = async () => {
  if (!sale_code.value.trim()) return;
  try {
    errorMsg.value = "";
    isLoading.value = true;
    const res = await axios.get(
      `${apiBasePharma}/order/order-tracking?sale_code=${sale_code.value.trim()}`,
    );
    if (res.data?.status === "error") {
      orderStatus.value = null;
      errorMsg.value = res.data?.message || "Order not found. Please check your order code.";
    } else {
      orderStatus.value = res.data;
    }
  } catch (error) {
    orderStatus.value = null;
    errorMsg.value = "Something went wrong. Please try again.";
    console.error("Error fetching order data:", error.message);
  } finally {
    isLoading.value = false;
  }
};

const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
};

const getStatusText = (status) => {
  const statusMap = {
    null: "Processing",
    1: "Store Arrived",
    2: "On The Way",
    3: "Delivered",
    4: "Not Reachable",
    5: "Not Received",
  };
  return statusMap[status] || "Processing";
};

const getStatusBadgeClass = (status) => {
  const classMap = {
    null: "bg-blue-50 text-blue-600",
    1: "bg-yellow-50 text-yellow-600",
    2: "bg-orange-50 text-orange-600",
    3: "bg-green-50 text-green-600",
    4: "bg-red-50 text-red-600",
    5: "bg-red-50 text-red-600",
  };
  return classMap[status] || "bg-blue-50 text-blue-600";
};

const getCurrentStep = () => {
  const stepMap = { null: 0, 1: 1, 2: 2, 3: 3, 4: 2, 5: 2 };
  return stepMap[orderStatus.value?.delivery_status] ?? 0;
};

onMounted(async () => {
  if (sale_code.value) {
    await trackOrder();
  }
});
</script>

<style lang="scss" scoped>
.animate-fade-in {
  animation: fadeIn 0.5s ease-out;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(12px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>
